- name: Lint Check
  hosts: localhost
  user: root
  become: yes
  gather_facts: false
  tasks:
    - name: install ansible lint
      apk:
        name: ansible-lint,jsonschema
        update_cache: true
    - name: Execute Lint Check
      command: ansible-lint --skip-list  fqcn-builtins install-apache2
